/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as WorkWithMeRouteImport } from './routes/work-with-me'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as KeyConceptsRouteImport } from './routes/key-concepts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkWithMeIndexRouteImport } from './routes/work-with-me.index'
import { Route as WorkWithMeSlugRouteImport } from './routes/work-with-me.$slug'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkWithMeRoute = WorkWithMeRouteImport.update({
  id: '/work-with-me',
  path: '/work-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyConceptsRoute = KeyConceptsRouteImport.update({
  id: '/key-concepts',
  path: '/key-concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkWithMeIndexRoute = WorkWithMeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkWithMeRoute,
} as any)
const WorkWithMeSlugRoute = WorkWithMeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkWithMeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/key-concepts': typeof KeyConceptsRoute
  '/resources': typeof ResourcesRoute
  '/work-with-me': typeof WorkWithMeRouteWithChildren
  '/writing': typeof WritingRoute
  '/work-with-me/$slug': typeof WorkWithMeSlugRoute
  '/work-with-me/': typeof WorkWithMeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/key-concepts': typeof KeyConceptsRoute
  '/resources': typeof ResourcesRoute
  '/writing': typeof WritingRoute
  '/work-with-me/$slug': typeof WorkWithMeSlugRoute
  '/work-with-me': typeof WorkWithMeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/key-concepts': typeof KeyConceptsRoute
  '/resources': typeof ResourcesRoute
  '/work-with-me': typeof WorkWithMeRouteWithChildren
  '/writing': typeof WritingRoute
  '/work-with-me/$slug': typeof WorkWithMeSlugRoute
  '/work-with-me/': typeof WorkWithMeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/key-concepts'
    | '/resources'
    | '/work-with-me'
    | '/writing'
    | '/work-with-me/$slug'
    | '/work-with-me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/key-concepts'
    | '/resources'
    | '/writing'
    | '/work-with-me/$slug'
    | '/work-with-me'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/key-concepts'
    | '/resources'
    | '/work-with-me'
    | '/writing'
    | '/work-with-me/$slug'
    | '/work-with-me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  KeyConceptsRoute: typeof KeyConceptsRoute
  ResourcesRoute: typeof ResourcesRoute
  WorkWithMeRoute: typeof WorkWithMeRouteWithChildren
  WritingRoute: typeof WritingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-with-me': {
      id: '/work-with-me'
      path: '/work-with-me'
      fullPath: '/work-with-me'
      preLoaderRoute: typeof WorkWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key-concepts': {
      id: '/key-concepts'
      path: '/key-concepts'
      fullPath: '/key-concepts'
      preLoaderRoute: typeof KeyConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-with-me/': {
      id: '/work-with-me/'
      path: '/'
      fullPath: '/work-with-me/'
      preLoaderRoute: typeof WorkWithMeIndexRouteImport
      parentRoute: typeof WorkWithMeRoute
    }
    '/work-with-me/$slug': {
      id: '/work-with-me/$slug'
      path: '/$slug'
      fullPath: '/work-with-me/$slug'
      preLoaderRoute: typeof WorkWithMeSlugRouteImport
      parentRoute: typeof WorkWithMeRoute
    }
  }
}

interface WorkWithMeRouteChildren {
  WorkWithMeSlugRoute: typeof WorkWithMeSlugRoute
  WorkWithMeIndexRoute: typeof WorkWithMeIndexRoute
}

const WorkWithMeRouteChildren: WorkWithMeRouteChildren = {
  WorkWithMeSlugRoute: WorkWithMeSlugRoute,
  WorkWithMeIndexRoute: WorkWithMeIndexRoute,
}

const WorkWithMeRouteWithChildren = WorkWithMeRoute._addFileChildren(
  WorkWithMeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  KeyConceptsRoute: KeyConceptsRoute,
  ResourcesRoute: ResourcesRoute,
  WorkWithMeRoute: WorkWithMeRouteWithChildren,
  WritingRoute: WritingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
